-- Prioridad alta (minuta 02/06/2026)
-- 1) Lotes: agregar estatus N = No disponible
-- 2) Pagos: agregar campo servicios/extra
-- 3) Transferencias: catálogo de cuentas bancarias + referencia en pagos

begin;

-- -----------------------------------------------------------------------------
-- Lotes: permitir estatus N (No disponible)
-- -----------------------------------------------------------------------------
-- Elimina checks conocidos si existen.
alter table public.lote drop constraint if exists lote_estatus_check;
alter table public.lote drop constraint if exists lote_check_estatus;

-- Crea check actualizado.
alter table public.lote
  add constraint lote_estatus_check
  check (estatus is null or estatus = any (array['D'::text, 'A'::text, 'V'::text, 'B'::text, 'N'::text]));

-- -----------------------------------------------------------------------------
-- Catálogo de cuentas bancarias para transferencias
-- -----------------------------------------------------------------------------
create table if not exists public.cuentas_bancarias (
  cuenta_bancaria_id bigint generated by default as identity primary key,
  nombre text not null,
  banco text,
  numero_cuenta text,
  clabe text,
  desarrolloid integer references public.desarrollo(desarrolloid) on delete set null,
  activa boolean not null default true,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Pagos: servicios/extra y cuenta bancaria destino
-- -----------------------------------------------------------------------------
alter table public.pagos
  add column if not exists servicios_extra numeric(12,2) not null default 0,
  add column if not exists cuenta_bancaria_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'pagos_cuenta_bancaria_id_fkey'
  ) then
    alter table public.pagos
      add constraint pagos_cuenta_bancaria_id_fkey
      foreign key (cuenta_bancaria_id)
      references public.cuentas_bancarias(cuenta_bancaria_id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_pagos_cuenta_bancaria_id on public.pagos(cuenta_bancaria_id);
create index if not exists idx_pagos_servicios_extra on public.pagos(servicios_extra);

commit;
